.MODEL SMALL
.STACK 100H
.CODE
MAIN	PROC
	MOV	AH,2		;OUT
	MOV	DL,'?'
	INT	21H		;GO OUT

	MOV	AH,1		;IN
	INT	21H		;GO IN

	MOV	BL,AL		;AL -> BL SAVE

	MOV	AH,2		;OUT
	MOV	DL,0DH		;<-
	INT	21H		;GO OUT
	MOV	DL,0AH		;NEXT LINE
	INT	21H		;GO OUT

	MOV	DL,BL		;(IN)
	INT	21H		;GO OUT (IN)
	INC	DL		;SAVE (NEXT (IN))
	INT	21H		;GO OUT

	MOV	AH,4CH
	INT	21H
MAIN	ENDP
	END	MAIN